Content:
    Lynx:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    name: LYNX
    repo: https://gitext.gfz-potsdam.de/ajacquey/lynx
    # home: https://www.mooseframework.org
    google_analytics: True

Translators:
    type: MooseDocs.base.Translator
    incremental_build: False

Extensions:
    MooseDocs.extensions.navigation:
        name: 'LYNX'
        repo: https://gitext.gfz-potsdam.de/ajacquey/lynx
        # home: https://www.mooseframework.org
        menu:
            Getting Started: getting_started/index.md
            Documentation: documentation.menu.md
            Help: help.menu.md
            # News: newsletter/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include