Content:
    Lynx:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**

Renderer:
    type: MooseDocs.base.MaterializeRenderer
    google_analytics: True

Translators:
    type: MooseDocs.base.Translator
    incremental_build: False

Extensions:
    MooseDocs.extensions.navigation:
        name: Lynx
        repo: https://github.com/ajacquey/lynx
        menu:
            Getting Started: getting_started/index.md
            Documentation: documentation.menu.md
            Help: help.menu.md
            # News: newsletter/index.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        includes:
            - include